# Generated by Django 3.1.5 on 2021-04-18 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('height_feet', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_inches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spotify_playlist_uri', models.CharField(blank=True, default='', max_length=50)),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Running', 'Running'), ('Weight Lifting', 'Weight Lifting'), ('Other', 'Other')], default='Running', max_length=50)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length', models.PositiveIntegerField(null=True)),
                ('total_weight_lifted', models.PositiveIntegerField(null=True)),
                ('distance', models.PositiveSmallIntegerField(null=True)),
                ('reps', models.PositiveIntegerField(null=True)),
                ('sets', models.PositiveIntegerField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outwork.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='outwork.userdata')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='outwork.userdata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follows',
            constraint=models.UniqueConstraint(fields=('userdata', 'is_following'), name='unique_followers'),
        ),
    ]
