# Generated by Django 3.1.5 on 2021-04-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwork', '0002_auto_20210418_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='total_weight_lifted',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
