# Generated by Django 3.1.5 on 2021-04-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outwork', '0003_auto_20210418_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
